# Generated by Django 4.0.6 on 2022-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
